import px from '../../Biz/px.js';
export default  {
    listContainer:{
        height:px(70),
        backgroundColor:'#fff'
    },
    statusText:{
        fontSize:px(26),
        fontFamily:'Microsoft YaHei',
    },
    faab89:{
        color:'#FF6000',
    },
    num:{
        fontSize:px(22),
    },
    dataHeaderItem:{
        paddingLeft:12,
        paddingRight:12,
        flexDirection:'row',
        marginLeft:px(10),
        marginRight:px(10),
        height:px(70),
        justifyContent:'center',
        alignItems:'center',
        fontWeight:'400',
    },
    arrowDown:{
        alignItems:'center',
        justifyContent:'center',
        width:99,
        height:60,
        position:'absolute',
        right:0,
        top:5,
        borderLeftWidth:px(1),
        borderLeftColor:'#e5e5e5',
        borderLeftStyle:'solid',
        backgroundColor:'#fff'
    },
    mask:{
        marginTop:100,
        flex:1,
        backgroundColor:'rgba(0,0,0,0.7)',
        justifyContent: 'flex-start',
    },
    body:{
        width: px(750),
        paddingTop:12,
        paddingBottom:12,
        paddingRight:24,
        paddingLeft:24,
        backgroundColor: '#ffffff',
    },
    arrowUp:{
        color:'#666666',
        fontWeight:px(100),
        marginRight:px(15),
    },
    funTitle:{
        fontSize:px(24),
        fontWeight:'400',
        color:'#666666',
    },
    funText:{
        fontSize:px(24),
        fontWeight:'400',
        color:'#ffffff',
    },
    gridcell:{
        height:px(55),
        backgroundColor:'#ffffff',
        justifyContent:'center',
        alignItems:'center',
        borderWidth:px(2),
        borderStyle:'solid',
        borderColor:'#e8e8e8',
        borderRadius:px(8),
        marginTop:px(10),
        marginRight:px(15),
    },
    girdActive:{
        height:px(55),
        backgroundColor:'#ff7300',
        justifyContent:'center',
        alignItems:'center',
        borderWidth:px(2),
        borderStyle:'solid',
        borderColor:'#e8e8e8',
        borderRadius:px(8),
        marginTop:px(10),
        marginRight:px(15),
    },
}
