import px from '../../../Biz/px.js';
export default  {
    listContainer:{
        height:px(70),
        backgroundColor:'#fff'
    },
    statusText:{
        fontSize:px(26),
    },
    faab89:{
        color:'#FF6000',
    },
    num:{
        fontSize:px(22),
    },
    dataHeaderItem:{
        paddingLeft:12,
        paddingRight:12,
        flexDirection:'row',
        marginLeft:px(10),
        marginRight:px(10),
        height:px(70),
        justifyContent:'center',
        alignItems:'center',
    },
    arrowDown:{
        alignItems:'center',
        justifyContent:'center',
        width:px(99),
        height:px(60),
        position:'absolute',
        right:px(0),
        top:px(5),
        borderLeftWidth:px(1),
        borderLeftColor:'#e5e5e5',
        backgroundColor:'#fff'
    },
    mask:{
        marginTop:px(100),
        flex:1,
        backgroundColor:'rgba(0,0,0,0.7)',
        justifyContent: 'flex-start',
    },
    body:{
        width: px(750),
        paddingTop:px(12),
        paddingBottom:px(12),
        paddingRight:px(24),
        paddingLeft:px(24),
        backgroundColor: '#ffffff',
    },
    funTitle:{
        fontSize:px(24),
        fontWeight:'400',
        color:'#666666',
    },
    funText:{
        fontSize:px(24),
        fontWeight:'400',
        color:'#ffffff',
    },
    gridcell:{
        height:px(55),
        backgroundColor:'#ffffff',
        justifyContent:'center',
        alignItems:'center',
        borderWidth:px(2),
        borderColor:'#e8e8e8',
        borderRadius:px(8),
        marginTop:px(10),
        marginRight:px(15),
    },
    girdActive:{
        height:px(55),
        backgroundColor:'#ff7300',
        justifyContent:'center',
        alignItems:'center',
        borderWidth:px(2),
        borderColor:'#e8e8e8',
        borderRadius:px(8),
        marginTop:px(10),
        marginRight:px(15),
    },
}
