export default {
    cardBack:{
        backgroundColor:'#f5f5f5',
        paddingRight:24,
        paddingBottom:24,
        paddingLeft:24
    },
    card:{
        backgroundColor:'#ffffff',
        borderRadius:24,
        paddingLeft:24,
        flex:1
    },
    firstLine:{
        borderBottomColor:'#f5f5f5',
        borderBottomStyle:'solid',
        borderBottomWidth:px(2),
        height:76,
        paddingRight:24,
        flexDirection:'row',
        alignItems:'center'
    },
    copyIcon:{
        fontSize:28,
        color: '#3089DC',
        height: 28,
        width: 28,
    },
    cardLine:{
        flexDirection:'row',
        paddingTop:18,
        paddingBottom:18,
        paddingRight:24,
        borderBottomColor:'#f5f5f5',
        borderBottomStyle:'solid',
        borderBottomWidth:px(2)
    },
    footLine:{
        flexDirection:'row',
        height:100,
        alignItems:'center',
        justifyContent:'flex-end'
    },
    footBtns:{
        width:px(162),
        height:px(64),
        borderRadius:px(32),
        marginRight:px(36)
    },
    littleTag:{
        width:88,
        height:36,
        borderColor:'#ff6000',
        borderStyle:'solid',
        borderWidth:px(1),
        backgroundColor:'#ffffff',
        borderRadius:4,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    littleTagText:{
        fontSize:24,
        color:'#FF6000'
    },
    priceLine:{
        flexDirection:'row',
        flex:1,
        justifyContent:'flex-end'
    },
    priceLineBox:{
        flex:1,
        flexDirection:'row',
        alignItems:'center',
        borderBottomColor:'#f5f5f5',
        borderBottomStyle:'solid',
        borderBottomWidth:px(2),
        paddingLeft:24,
        paddingRight:24,
    },
    skuTag:{
        flexDirection:'row',
        backgroundColor:'#f5f5f5',
        paddingLeft:8,
        paddingRight:8,
        paddingTop:8,
        paddingBottom:8,
        borderRadius:4
    },
    littleBtn:{
        width:168,
        height:48,
        borderRadius:24,
        borderColor:'#ff6000',
        borderStyle:'solid',
        borderWidth:px(2),
        color:'#ff6000',
        fontSize:px(24)
    },
    priceLine:{
        flexDirection:'row',
        alignItems:'center',
        marginTop:px(12),
    },
    priceTag:{
        position:'absolute',
        right:0,
        top:28,
    },
    noMateTag:{
        position:'absolute',
        right:0,
        top:28,
        height:24,
        width:120,
        backgroundColor:'#ff6000',
        borderRadius:4,
        alignItems:'center',
        justifyContent:'center'
    },
}
