import px from '../../../Biz/px.js';
export default {
    shopLine:{
        borderBottomColor:'#f5f5f5',
        borderBottomWidth:px(2),
        paddingLeft:px(24),
        paddingRight:px(24),
        paddingTop:px(18),
        paddingBottom:px(18),
        backgroundColor:'#fff',
        flexDirection:'row',
        alignItems:'center',
        width:px(750),
        marginTop:px(24)
    },
    titleText:{
        color:'#000',
        fontSize:px(28),
        fontWeight:'600'
    },
    descText:{
        color:'#666',
        fontSize:px(24),
        marginLeft:px(24)
    },
    switchLine:{
        flex:1,
        flexDirection:'row',
        justifyContent:'flex-end',
        alignItems:'center',
    }
};
