import px from '../../Biz/px.js';
export default {
    firstLine:{
        borderTopWidth:px(1),
        borderTopColor:'#e5e5e5',
        borderTopStyle:'solid',
        borderBottomWidth:px(1),
        borderBottomColor:'#e5e5e5',
        borderBottomStyle:'solid',
        flexDirection:'row',
        alignItems: 'center',
        height: px(75),
        paddingLeft: px(20),
        paddingRight: px(24),
    },
    orderNum:{
        borderBottomWidth:px(1),
        borderBottomColor:'#e5e5e5',
        borderBottomStyle:'solid',
        height: px(75),
        alignItems: 'center',
        flexDirection: 'row',
        paddingLeft:24,
        paddingRight:24,
        paddingBottom:24,
        paddingTop:24,
        fontSize: px(24),
        color: '#333',
        fontWeight: '200',
    },
    errorLine:{
        borderBottomWidth:px(1),
        borderBottomColor:'#e5e5e5',
        borderBottomStyle:'solid',
        paddingLeft:24,
        paddingRight:24,
        paddingBottom:24,
        paddingTop:24,
        alignItems: 'center',
        flexDirection: 'row',
        fontSize: px(24),
        color: '#333',
        fontWeight: '200',
    },
    orderText:{
        color: '#999',
        fontSize: px(24),
    },
    number:{
        fontWeight:'normal',
        color:'#333',
        fontSize: px(24),
    },
    copy:{
        fontSize: px(18),
        color: '#666',
        marginLeft: px(8),
    },
    time:{
        color: '#999',
        marginLeft: px(12),
        fontSize: px(24),
        flex:1,
    },
    totals:{
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        borderTopWidth:px(1),
        borderTopColor:'#e5e5e5',
        borderTopStyle:'solid',
        borderBottomWidth:px(1),
        borderBottomColor:'#e5e5e5',
        borderBottomStyle:'solid',
        color: '#575757',
        height: px(75),
        paddingLeft:24,
        paddingRight:24,
        paddingBottom:24,
        paddingTop:24,
        fontSize: 24,
        marginTop: px(-1),
        //font-family: 'Microsoft YaHei',
    },
    buyerFeedback:{
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth:px(1),
        borderBottomColor:'#e5e5e5',
        borderBottomStyle:'solid',
        height: px(75),
        paddingLeft:24,
        paddingRight:24,
        paddingBottom:24,
        paddingTop:24,
        fontSize: 24,
    },
    logists:{
        justifyContent:'space-between',
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth:px(1),
        borderBottomColor:'#e5e5e5',
        borderBottomStyle:'solid',
        height: px(72),
        paddingLeft:24,
        paddingRight:24,
    },
    logists2:{
        height:140,
        backgroundColor:'#fff',
        paddingLeft:24,
        paddingRight:24,
        paddingTop:18,
        paddingBottom:18,
    },
    logistMess:{
        flexDirection: 'row',
        flex:1,
    },
    details:{
        flexDirection: 'row',
        alignItems: 'center',
    },
    detailText:{
        color: '#b4b4b4',
        fontSize: px(24),
        fontWeight: '200',
    },
    dackIcon:{
        position: 'absolute',
        right: px(20),
        top: '12',
        fontSize: '45',
        color: '#cecece',
        textAlign: 'right',
    },
    new:{
        height: px(24),
        width: px(24),
    },
    memoIcon:{
        flex:1,
        fontSize:40,
    },
    tagBox:{
        width:88,
        height:36,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        borderColor:'#ff6000',
        borderWidth:px(1),
        borderStyle:'solid',
        marginLeft:8
    },
    tagText:{
        fontSize:24,
        color:'#ff6000'
    },
    mask:{
        backgroundColor:'transparent'// 可以修改默认的灰底
    },
    categoryModel:{
        width: px(750),
        position:'absolute',
        height:px(750),
        left:0,
        right:0,
        bottom:0
    },
    body: {
        flex:1,
        backgroundColor: '#ffffff',
    },
    footer: {
        borderTopColor:'#dddddd',
        flexDirection:'row',
        borderTopStyle:'solid',
        borderTopWidth:1,
        alignItems: 'center',
        justifyContent: 'flex-end',
        height: px(94)
    },
    dlgBtn:{
        flex:1,
    },
    closeTag:{
        position:'absolute',
        right:24,
        top:34,
        fontSize:28,
        color:'#999999'
    }

}
