import px from '../../Biz/px.js';
export default {
    btn_normal:{
        borderRadius:px(8),
        backgroundColor:'#ffffff',
        borderColor:'#D8D8D8',
        borderWidth:px(1),
        alignItems:'center',
        justifyContent:'center',
    },
    btn_primary:{
        borderRadius:px(8),
        backgroundColor:'#ffffff',
        borderColor:'#ff6000',
        borderWidth:px(1),
        alignItems:'center',
        justifyContent:'center',
        paddingLeft:px(24),
        paddingRight:px(24),
        paddingTop:px(12),
        paddingBottom:px(12),
    },
    btn_secondary:{
        borderRadius:px(8),
        backgroundColor:'#ff6000',
        borderColor:'#ff6000',
        borderWidth:px(1),
        alignItems:'center',
        justifyContent:'center',
    },
    btn_disabled:{
        borderRadius:px(8),
        backgroundColor:'#F6F7F9',
        borderColor:'#E2E3E8',
        borderWidth:px(1),
        alignItems:'center',
        justifyContent:'center',
    },
    btn_warning:{
        borderRadius:px(8),
        backgroundColor:'#ff0000',
        borderColor:'#ff0000',
        borderWidth:px(1),
        alignItems:'center',
        justifyContent:'center',
    },
    text_normal:{
        color:'#5B5B6A',
        fontSize:px(24)
    },
    text_primary:{
        color:'#ff6000',
        fontSize:px(24)
    },
    text_secondary:{
        color:'#ffffff',
        fontSize:px(24)
    },
    text_warning:{
        color:'#ffffff',
        fontSize:px(24)
    },
    text_disabled:{
        color:'#C5C5C5',
        fontSize:px(24)
    },
}
