import px from '../../Biz/px.js';
export default {
    topswitch:{
        flexDirection:'row',
        width:px(750),
        height:96,
        alignItems:'center',
        justifyContent:'space-between',
        marginTop:24,
        backgroundColor:"#ffffff",
        paddingLeft:24,
        paddingRight:24,
    },
    topswitchText:{
        fontSize:32,
        color:'#4A4A4A'
    },
    blocktext:{
        fontSize:28,
        color:'#666666',
        paddingLeft:24,
        height:80,
        lineHeight:80,
        marginTop:12,
    },
    groupWrap:{
        backgroundColor:'#ffffff',
        flexDirection:'column',
        paddingLeft:12
    },
    groupitem:{
        height:86,
        backgroundColor:'#ffffff',
        flexDirection:'row',
        alignItems:'center',
        paddingLeft:12
    },
    switchBox:{
        width:200,
        height:96,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-end'
    },
    switchBoxDisable:{
        width:200,
        height:96,
        position:'absolute',
        top:0,
        right:0
    },
    topLine:{
        flexDirection:'row',
        width:px(750),
        height:120,
        paddingLeft:24,
        paddingRight:24,
        alignItems:'center',
        backgroundColor:'#f5f5f5'
    },
    addIcon: {
        fontSize:60,
        color:'#2357ff'
    },
    shopLine:{
        borderBottomColor:'#f5f5f5',
        borderBottomStyle:'solid',
        borderBottomWidth:px(2),
        height:170,
        paddingLeft:24,
        paddingRight:24,
        flexDirection:'row',
        alignItems:'center',
        width:750
    },
    shopImage:{
        width:82,
        height:82,
        borderRadius:8
    },
    footLine:{
        position:'fixed',
        bottom:0,
        left:0,
        right:0,
        height:96,
        flexDirection:'row',
        borderTopColor:'#e5e5e5',
        borderTopStyle:'solid',
        borderTopWidth:px(1)
    },
    footLeft:{
        backgroundColor:'#ffffff',
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    footRight:{
        backgroundColor:'#ff6000',
        flex:1,
        alignItems:'center',
        justifyContent:'center'
    },
    maskStyle:{
        backgroundColor:'rgba(0,0,0,0.5)'
    },
    modal2Style:{
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,0,0,0)'
    },
    dialogContent:{
        flex:1,
        borderRadius: px(8),
        backgroundColor: '#fff',
        paddingTop:px(20),
        width: px(612)
    },
    foot:{
        width:px(612),
        flexDirection:'row',
        height:px(96),
        marginTop:px(20)
    },
    cancelBtn:{
        width:px(306),
        height:px(96),
        borderTopWidth:px(2),
        borderStyle:'solid',
        borderColor:'#DCDEE3',
        alignItems:'center',
        justifyContent:'center',
        borderBottomLeftRadius:px(8)
    },
    submitBtn:{
        width:px(306),
        height:px(96),
        borderTopWidth:px(1),
        borderTopStyle:'solid',
        borderTopColor:'#DCDEE3',
        alignItems:'center',
        justifyContent:'center',
        borderBottomRightRadius:px(8)
    },
    fontStyle:{
        fontSize:px(32),
        color:'#272636'
    },
    addBtn:{
        flexDirection:'column',
        borderStyle:'dashed',
        borderColor:'#E5E5E5',
        borderWidth:px(4),
        borderRadius:px(8),
        alignItems:'center',
        justifyContent:'center',
        width:200,
        height:200,
        marginTop:24
    },
    tagImage:{
        width:80,
        height:80,
        borderRadius:8,
        borderStyle:'solid',
        borderWidth:2,
        borderColor:'#E5E5E5',
        marginTop:24,
        marginRight:32,
        alignItems:'center',
        justifyContent:'center'
    },
    tagImageActive:{
        width:80,
        height:80,
        borderRadius:8,
        borderStyle:'solid',
        borderWidth:2,
        borderColor:'#0077FF',
        marginTop:24,
        marginRight:32,
        alignItems:'center',
        justifyContent:'center'
    },
    dialogBody:{
        paddingTop:28,
        paddingLeft:40,
        paddingRight:40
    },
    borderLine:{
        borderBottomColor:'#E5E5E5',
        borderBottomStyle:'solid',
        borderBottomWidth:2,
        marginTop:56,
        paddingBottom:8
    },
    tokenBody:{
        height:216,
        paddingLeft:40,
        paddingRight:40,
        alignItems:'center',
        justifyContent:'center'
    },
    refresh: {
        width: px(750),
        height:80,
        backgroundColor: '#ffffff',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        color: '#3089dc',
    },
    authError:{
        position:'absolute',
        top:112,
        left:204
    },
    WDinput:{
        width:500,
        height:50,
        borderBottomColor:'#333333',
        borderBottomStyle:'solid',
        borderBottomWidth:2,
        borderTopColor:'#E5E5E5',
        borderTopStyle:'solid',
        borderTopWidth:0,
        borderLeftColor:'#E5E5E5',
        borderLeftStyle:'solid',
        borderLeftWidth:0,
        borderRightColor:'#E5E5E5',
        borderRightStyle:'solid',
        borderRightWidth:0,

    },
    WDinputout:{
        height:50,
        marginTop:50,
        alignItems:'center',
        justifyContent:'center',
        flexDirection:'row',
    }
};
