import px from '../../Biz/px.js';
export default {
    commonLine:{
        flex:1,
        backgroundColor:'#EEEEEE',
    },
    skuone:{
        height:232,
        backgroundColor:'#ffffff',
        paddingLeft:24,
        paddingRight:24,
        marginBottom:2,
    },
    head:{
        height: 50,
        alignItems: 'flex_start',
        justifyContent: 'center',
        marginTop:20,
        // marginLeft:20,
    },
    textHead:{
        color:'#3d4145',
        fontSize:32,
    },
    skuoneTop:{
        height:84,
        borderBottomColor:'#CCCCCC',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        borderBottomStyle:'solid',
        borderBottomWidth:px(2),
    },
    skuoneMid:{
        height:84,
        borderBottomColor:'#CCCCCC',
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        borderBottomStyle:'solid',
        borderBottomWidth:px(2),
    },
    skuoneBot:{
        height:56,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-end',

    },
    skuoneTopLeft:{
        fontFamily: 'PingFangSC-Regular',
        fontSize: 28,
        color: '#333333',
    },
    skuoneTopRight:{
        fontFamily: 'PingFangSC-Regular',
        fontSize: 28,
        color: '#3089DC',
    },
    skuoneMidtext:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
    },
    skuoneMidtextLeft:{
        fontFamily: 'PingFangSC-Regular',
        fontSize: 28,
        color: '#999999',
    },
    skuoneMidtextRight:{
        fontFamily: 'PingFangSC-Regular',
        fontSize: 28,
        color: '#333333',
    },
    skuoneBotleft:{
        fontFamily: 'PingFangSC-Regular',
        fontSize: 28,
        color: '#999999',
    },
    skuoneBotmid:{
        fontFamily: 'PingFangSC-Regular',
        fontSize: 28,
        color: '#FF6000',
    },
    input:{
        marginTop:20,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'flex-start',
    },
    inputText:{
        fontFamily: 'PingFangSC-Regular',
        fontSize: 28,
        color: '#4A4A4A',
        // height:30,
    },
    footer: {
        height:82,
        borderTopColor:'#dddddd',
        flexDirection:'row',
        borderTopStyle:'solid',
        borderTopWidth:1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    body:{
        paddingLeft:32,
        paddingRight:32,
        paddingBottom:32,
        backgroundColor:'#ffffff',
        borderBottomStyle:'solid',
        borderBottomWidth:px(1),
        borderBottomColor:'#CCCCCC',
        // position:'fixed',
        // top:300,
        // left:0,
        // width:px(750),
        // height:250,
    },
    tips:{
        marginTop:14,
        marginBottom:44,
        fontFamily: 'PingFangSC-Regular',
        fontSize: 24,
        color: '#979797',
    },
}
