import px from '../../Biz/px.js';
export default{
    dialogContainer:{
        width:px(570),
        backgroundColor:'#ffffff',
        borderRadius:px(8)
    },
    dialogContainer2:{
        width:px(500),
        minHeight:px(156),
        backgroundColor:'#ffffff',
        borderRadius:px(8),
    },
    dialogTitle:{
        width:px(570),
        height:px(50),
        marginTop:px(30),
        paddingLeft:px(30),
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
    },
    dialogTitleText:{
        fontSize:px(36),
        color:'#333333'
    },
    dialogBody:{
        width:px(570),
        flex:1,
        paddingTop:px(30),
        paddingBottom:px(30),
        paddingLeft:px(35),
        paddingRight:px(25),
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center'
    },
    dialogBody2:{
        width:px(580),
        height:px(156),
        flexDirection:'row',
        alignItems:'center',
        paddingRight:px(32)
    },
    dialogBodyText:{
        fontSize:px(32),
        color:'#5F646E',
        width:px(510),
    },
    dialogBodyText2:{
        width:px(380),
        fontSize:px(32),
        color:'#333333',
    },
    dialogButton:{
        height:px(80),
        paddingTop:px(30),
        paddingBottom:px(30),
        paddingLeft:px(30),
        paddingRight:px(30),
        borderTopWidth:px(1),
        borderTopColor:'#DCDEE3',
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
    },
    dialogButtonText:{
        fontSize:px(32),
        color:'#333333'
    }
}
